pipeline {
agent any
environment {
    JAVA_HOME="C:/jdk-21.0.9"
  }
stages {
stage('Clean stage') {
steps {
dir("StockApp") {
bat 'C:/apache-maven-3.9.16-bin/apache-maven-3.9.16/bin/mvn clean'
}
}
}

stage('Compile stage') {
steps {
dir("StockApp") {
bat 'C:/apache-maven-3.9.16-bin/apache-maven-3.9.16/bin/mvn compile'
}
}
}

stage('Install stage') {
steps {
dir("StockApp") {
bat 'C:/apache-maven-3.9.16-bin/apache-maven-3.9.16/bin/mvn install'
}
}
}

}
}
